import type { Config } from 'tailwindcss'
import plugin from 'tailwindcss/plugin'

export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#00685d',
        secondary: '#295ab9',
        tertiary: '#116a30',
        background: '#f6faf8',
        surface: '#f6faf8',
        'on-surface': '#171d1b',
        'on-surface-variant': '#3d4947',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        'primary-fixed': '#8cf5e4',
        'primary-fixed-dim': '#6fd8c8',
        'primary-container': '#008376',
        'on-primary-container': '#f4fffb',
        'secondary-container': '#719bfe',
        'on-secondary-container': '#00317a',
        'secondary-fixed': '#dae2ff',
        'secondary-fixed-dim': '#b1c5ff',
        'on-secondary-fixed': '#001946',
        'on-secondary-fixed-variant': '#00419d',
        'tertiary-container': '#328447',
        'tertiary-fixed': '#a1f6ac',
        'tertiary-fixed-dim': '#86d992',
        'on-tertiary-container': '#f7fff3',
        'on-tertiary-fixed': '#002109',
        'on-tertiary-fixed-variant': '#005322',
        'surface-bright': '#f6faf8',
        'surface-dim': '#d6dbd9',
        'surface-variant': '#dfe4e1',
        'surface-tint': '#006a60',
        'surface-container': '#eaefec',
        'surface-container-low': '#f0f5f2',
        'surface-container-high': '#e4e9e7',
        'surface-container-highest': '#dfe4e1',
        'surface-container-lowest': '#ffffff',
        outline: '#6d7a77',
        'outline-variant': '#bcc9c6',
        'inverse-surface': '#2c3130',
        'inverse-primary': '#6fd8c8',
        'inverse-on-surface': '#edf2ef',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'on-background': '#171d1b',
        'on-primary-fixed': '#00201c',
        'on-primary-fixed-variant': '#005048',

        // Semantic aliases — use these in components instead of raw hex
        'primary-dark': '#004d40',
        'primary-darker': '#003028',
        accent: '#6fd8c8',
        'surface-muted': '#EAF5F1',
        'surface-light': '#f0f5f2',
      },
      spacing: {
        unit: '4px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        gutter: '16px',
        lg: '24px',
        xl: '40px',
        xxl: '64px',
        'container-margin': '20px',
      },
      fontFamily: {
        h1: ['"Plus Jakarta Sans"', 'sans-serif'],
        h2: ['"Plus Jakarta Sans"', 'sans-serif'],
        h3: ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        button: ['Inter', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-caps': ['0.7rem',  { lineHeight: '1',   letterSpacing: '0.05em', fontWeight: '600' }],
        'body-sm':    ['0.8rem',  { lineHeight: '1.5', fontWeight: '400' }],
        'body-md':    ['0.9rem',  { lineHeight: '1.5', fontWeight: '400' }],
        'body-lg':    ['1rem',    { lineHeight: '1.6', fontWeight: '400' }],
        h3:           ['1.1rem',  { lineHeight: '1.4', fontWeight: '600' }],
        h2:           ['1.35rem', { lineHeight: '1.3', fontWeight: '600' }],
        h1:           ['1.75rem', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        button:       ['0.9rem',  { lineHeight: '1',   fontWeight: '600' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      keyframes: {
        'float-slow': {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-12px)' },
        },
        'float-slow-reverse': {
          '0%, 100%': { transform: 'translateY(-8px)' },
          '50%': { transform: 'translateY(0px)' },
        },
        'breathing-pulse': {
          '0%, 100%': { transform: 'scale(1)', opacity: '0.6' },
          '50%': { transform: 'scale(1.15)', opacity: '1' },
        },
        wave: {
          '0%': { transform: 'translateX(0) scaleY(1)' },
          '50%': { transform: 'translateX(-25%) scaleY(0.8)' },
          '100%': { transform: 'translateX(-50%) scaleY(1)' },
        },
        'glow-pulse': {
          '0%, 100%': { boxShadow: '0 0 20px rgba(0, 104, 93, 0.3)' },
          '50%': { boxShadow: '0 0 40px rgba(0, 104, 93, 0.6), 0 0 60px rgba(0, 104, 93, 0.3)' },
        },
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        spin: {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
      },
      animation: {
        'float-slow': 'float-slow 6s ease-in-out infinite',
        'float-slow-2': 'float-slow 7s ease-in-out infinite 1s',
        'float-slow-3': 'float-slow 8s ease-in-out infinite 2s',
        'float-slow-reverse': 'float-slow-reverse 6s ease-in-out infinite 0.5s',
        'breathing-pulse': 'breathing-pulse 4s ease-in-out infinite',
        'breathing-pulse-2': 'breathing-pulse 4s ease-in-out infinite 1.3s',
        'breathing-pulse-3': 'breathing-pulse 4s ease-in-out infinite 2.6s',
        wave: 'wave 8s linear infinite',
        'wave-slow': 'wave 12s linear infinite',
        'glow-pulse': 'glow-pulse 3s ease-in-out infinite',
        'fade-in-up': 'fade-in-up 0.6s ease-out forwards',
      },
      rotate: {
        '8': '8deg',
        '-8': '-8deg',
      },
    },
  },
  plugins: [
    plugin(function ({ addUtilities }) {
      addUtilities({
        '.no-scrollbar': {
          '-ms-overflow-style': 'none',
          'scrollbar-width': 'none',
          '&::-webkit-scrollbar': {
            display: 'none',
          },
        },
        '.glass-nav': {
          background: 'rgba(246, 250, 248, 0.85)',
          'backdrop-filter': 'blur(20px)',
          '-webkit-backdrop-filter': 'blur(20px)',
          'border-bottom': '1px solid rgba(188, 201, 198, 0.3)',
        },
        '.glass-card': {
          background: 'rgba(255, 255, 255, 0.85)',
          'backdrop-filter': 'blur(20px)',
          '-webkit-backdrop-filter': 'blur(20px)',
          border: '1px solid rgba(255, 255, 255, 0.5)',
          'box-shadow': '0 8px 32px 0 rgba(0, 0, 0, 0.1)',
        },
        '.glass-card-dark': {
          background: 'rgba(0, 0, 0, 0.2)',
          'backdrop-filter': 'blur(20px)',
          '-webkit-backdrop-filter': 'blur(20px)',
          border: '1px solid rgba(255, 255, 255, 0.15)',
        },
        '.serenity-gradient': {
          background: 'linear-gradient(135deg, #003028 0%, #004d46 50%, #003028 100%)',
        },
        '.ambient-shadow': {
          'box-shadow': '0 4px 24px rgba(0, 104, 93, 0.15), 0 1px 4px rgba(0, 104, 93, 0.1)',
        },
        '.feature-card-hover': {
          transition: 'transform 0.3s ease, box-shadow 0.3s ease',
          '&:hover': {
            transform: 'translateY(-5px)',
            'box-shadow': '0 20px 40px rgba(0, 104, 93, 0.2)',
          },
        },
        '.section-gradient-light': {
          background: 'linear-gradient(135deg, #f0f5f2 0%, #f6faf8 50%, #eaefec 100%)',
        },
      })
    }),
  ],
} satisfies Config
